### ISSUE TITLE
[Suggestion] Searching Celestial Bodies

### ISSUE THREAD

**Issue by D4RKN3R** [Nettakrim/Spyglass-Astronomy#40]
This feels like it would be simple to add, but I don't code mods for Minecraft, so I'd have no idea.
Being able to run a command to select the body matching a specific set criteria (like, for instance, the closest star to the Minecraft planet or brightest from it out of the potentially thousands of stars) would be a huge help so that people don't manually sift through thousands of stars just to find the closest one.

Thank you.

**Comment by Nettakrim** [comment]
iirc theres a way to indirectly select stars by index, and stars with lower indexes are on average closer because of how it generates

the most immersive astronomer-y solution *would* be to manually check stars and add them to a spreadsheet, then filter from there, which has the advantage of allowing the player to mark subjective information

**Comment by Nettakrim** [comment]
yeah if you do `/sga:admin name star <index> <name>` it will automatically select it
